# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180507_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='ticket',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
